### ISSUE TITLE
AEQueue encoding error on Mac

### ISSUE THREAD

**Issue by danbradham** [nybrandnewschool/tk-aftereffects-queue#5]
```
  anim_seqa_031_v028
  queued [  0%] Flow initialized...
   ├ waiting [  0%] rendering initialized...
   ├ waiting [  0%] encoding MP4 initialized...
   ├ waiting [  0%] encoding GIF initialized...
   ├ waiting [  0%] copying MP4 initialized...
   ├ waiting [  0%] copying GIF initialized...
   ├ waiting [  0%] uploading initialized...
  queued [  0%] Waiting for requirements...
  rendering [  0%] Upstream Dependencies satisfied...
  rendering [  0%] Status changed from WAITING to RUNNING.
  rendering [  0%] Setting context...
  rendering [  0%] Starting...
   ├ running [  0%] Status changed from WAITING to RUNNING.
   ├ running [  0%] Preparing output path...
   ├ running [ 40%] Setting Full Flat Path: /Volumes/GoogleDrive/Shared drives/22-XXX-TestA/animation/renders/ae/seqA/seqa_031/anim_seqa_031_v028.mov
   ├ running [ 40%] Rendering [BNS - ProRes 4444+]
   └ success [100%] Status changed from RUNNING to SUCCESS.
  encoding MP4 [ 16%] Setting context...
  encoding MP4 [ 16%] Starting...
   ├ running [  0%] Status changed from WAITING to RUNNING.
   └ failed [  0%] Task failed to execute...
Traceback (most recent call last):
  File "/Users/Edit/Library/Caches/Shotgun/bundle_cache/github/nybrandnewschool/tk-aftereffects-queue/v0.3.0/python/aequeue/tasks/core.py", line 226, in run
    self.result = self.execute()
  File "/Users/Edit/Library/Caches/Shotgun/bundle_cache/github/nybrandnewschool/tk-aftereffects-queue/v0.3.0/python/aequeue/tasks/encode.py", line 73, in execute
    self.dst_file,
  File "/Users/Edit/Library/Caches/Shotgun/bundle_cache/github/nybrandnewschool/tk-aftereffects-queue/v0.3.0/python/aequeue/vendor/ffmpeg_lib/__init__.py", line 125, in encode
    **platform_kwargs
  File "/Applications/Shotgun.app/Contents/Resources/Python3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Applications/Shotgun.app/Contents/Resources/Python3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'ffmpeg'
   └ failed [  0%] Status changed from RUNNING to FAILED.
  encoding MP4 [ 16%] Status changed from RUNNING to FAILED.
```

**Comment by danbradham** [comment]
This was a simple permissions error, the ffmpeg executable needed execute permissions on the user's machine.
